---
bibliography: references.bib
---

# Introduction {#intro}

We do rigorous quantitative science to support decision-making for living marine resource management. We conduct our work using Open Data Science principles, emphasizing scientific excellence (not perfection) that is transparent, reproducible, collaborative, and ethical. We aim to make our methods and results available and support ongoing learning.\
Our quantitative work is based on statistical thinking, using evidence-based approaches to compare among alternatives for models and management options.

See the next chapter for more detail on our team culture and philosophy. We are motivated heavily by the following two papers - which provide a blueprint for how we think about the way we do our work:

- Our path to better science in less time using open data science tools [@lowndes2017]
- Good enough practices in scientific computing [@wilson2017]

\[To come: recommended reading list\]

## How we meet

Currently, we meet virtually through teams daily (standup 15 min + code preview 40 min, be human 5 min), Tidy Tuesday ( 60 min code improvement), Rstudio Hangouts ( lunch and learn 60 min on thursday) .\
We use MS Teams to set agendas, record decisions made, and outline action items during meetings. Each member has their own OneNote.

## How we give feedback

Feedback, both giving and receiving it, is an important aspect of our team. Most of the feedback we give and receive is when giving and attending code reviews. We expect feedback to be supportive but constructive.

This [resource from UBC](https://scwrl.ubc.ca/student-resources/learning-strategies-for-communicating-science/how-to-give-and-receive-effective-feedback/) does a really great job of outlining the main points of how to give and receive feedback.

## How we share things 

We think it is useful to have standard ways of sharing things. These don't always have to be followed but are a useful guide and will make things easier. When sending material to someone, always make sure to describe what you are sending and try to make it as easy as possible for them to help you.

Taking a project-based approach to organizing your work makes it easier to share and solicit feedback from others, as things tend to be self-contained. Try to keep only 1 working instance of material, and use some form of version control to facilitate this (see recommendations in Wilson et. al paper linked above).

Project management tools in Azure Dev Ops are a good way to record and document questions on analyses. Use 'Issues' on repositories for project-related tasks and problems.[resource from Tidyverse](https://reprex.tidyverse.org/)

Code: can be shared via Azure Dev Ops repositories. For specific questions on problems, please try to create a minimal reproducible example. Ensure that others can run and interact with the material being shared. Please us reprex

We also share our institutional knowledge through our Data Science Team Chat. This is a community-driven troubleshooting resource, please contribute!

## Shared lab resources

Where to find shared resources: - OneNote Data Science Notebook - You will be given access to the shared drive during onboarding

## References

