# Expectations {#expectations}

In addition to agreeing to follow our communities codes of conduct and the university academic integrity policy, we expect everyone in the group to echo our team culture (Chapter \@ref(culture)). 

__Individual mentoring plans:__  Your manager will work with each of you to develop your individual mentoring plan that serves to ensure your time in vRad progresses your short, medium, and long-term goals. This is a useful planning document that assists in aligning expectations. Revisit the mentoring plan during an individual meeting with your manager at the beginning of each year & the start of summer.  
A template for these, with thanks to [`@duffy_ma`](https://twitter.com/duffy_ma) can be found [here](https://docs.google.com/document/d/1ie3nc6iqW5cWit_MV8BUIVmREbvUZ8b0P9dR8CGgleQ/edit?usp=sharing).

In addition, it is useful to have broad (for all members) and specific (i.e. staff) expectations of our roles clarified. These are outlined below.  

## Working hours

vRad generally does not hold people to working a fixed schedule, or to be in the online for a certain schedule. As adults, we should all set the working schedule that is the right fit for us, and it is likely that what this 'fit' is will change over the course of the time you are in vRad. Depending on the nature of your appointment, there may be specific hours that will need to be worked. You should work with your manager and team members to outline these.  

At vRad we generally do not work evenings or on weekends, and do not expect that people in the DS team are available at these times. Team members should also not expect others to be available during these times.   

Team members are generally funded from a specific departements budget to serve the overall goals of the broader organization. Salaried employes are expected to contribute a minimum of 70% of work hours on projects and tasks aligned with teams current urgency and priority. The nature of Data science allows, and requires profesional development in technical and associate skill in addition to thos required by existing tasks. To meet expectations at least 10% of time is allowed for personal and professional development to increase indivdual value in alignment with the teams outlook of continuos development. We believe that training to do the work is part of the job, so this would include courses and additional time to read/learn methods, software too. DataCamp is the current platform by which the organization allows for continual skill building; USE IT! Some people find that counting 'billable hours' is productive for them as it helps them keep accountable to themselves. Others do not find this method useful. Regularly assess what works best for you.  

Full time is enough, and we do not expect team members to work nights and weekends, though do not enforce a particular working hours schedule because students should feel flexible enough to create a work schedule that works for them. Lab members should not expect others to be available during evenings and weekends. There is value to interacting with others as part of your work, and we do expect you will be available during normal working hours for at least some of the time during the week. We also recognize that there will occasionally be times where there is a need to work more to meet a deadline, but this should be the exception - an expectation of overwork is not to be normalized.  


## Email

At vRad, we communicate via email. You should therefore check your email at least once a day during the normal work week. We also make use of MS Teams and OneNote to record institutional knowledge and hold conversations regarding tasks. Note that being available does not mean that you are available 24/7 - this is not expected. Do not expect responses to emails after regular business hours on weekdays, or on weekends. However, because we recognize that team members should be able to create a working schedule that is right for them, team members should not be penalized for sending communication during these times.   


## Attendance at regularly scheduled events

Attendance is expected at:

* Departmental meetings  
* Weekly Check-in meetings with manager
* Daily standup meetings to discuss and work on active projects.  
* Annual Rad retreat


## Outreach

We share our learning and time with others beyond our company, knowing that this builds community and ultimately improves both the quality and impact of our work. This doesn’t mean individuals do everything, however. We take on leadership roles within vRad, are supportive of others in our community during their milestones, actively participate in vRad events, and perform outreach. Ask others in the team about activities they are part of, and work with your manager when crafting your mentoring plan to identify outreach strategy that meshes well with your goals.  


## Expectations for the Manager

Your manager will (at a minimum) provide:  

* Technical support for analysis (e.g., access to computing, training on techniques)  
* Positive feedback & constructive criticism on work  
* Professional career support  
* Support for non-technical aspects of making career progress  
* Regular meetings (every two weeks) to discuss work & maintain progress on goals  
* Provide clear and honest appraisal of your employment situation  


## Team members

Team members operate as independent and collaborative partners on assigned projects. As these positions are often working directly alongside your direct collaborator on particular team projects, meetings may be more frequent than those with others in the team. Weekly meetings should have clear agendas, and can often be used as collaborative working time to make progress on specific tasks. 

In general, team members are expected to:

* Be present and involved in meetings, workshops, amd seminars
* Provide technical support and assistance to other team members
* Communicate both successes and sticking points on a regular basis with manager
* Work independently and collaboratively
* Lead and assist in designated projects
* Participate in professional development opportunities (i.e., workshops, conferences)
* Seek and pursue new business opportunities when appropriate (this will likely be dependent on your maturity)
* Produce expected output from assigned projects
* Be flexible! Additional projects may be assigned to give additional funding for your position  
* Serve as a role model and go-to resource for other members of the team

Exact set of responsibilities and duties will be clearly defined in your position description and expectations agreed on in your work plan.  
